import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
// import { ThemeProvider } from "next-themes";
// import Footer from "@/components/layout/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "ポートフォリオ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* <ThemeProvider
					attribute="data-theme"
					// defaultTheme="light"
					// enableSystem={false}
					// themes={["light", "dark"]}
				></ThemeProvider> */}
				<div className="min-h-screen flex flex-col">
					<Header />
					<main className="flex-grow">{children}</main>
				</div>
			</body>
		</html>
	);
}
